# Generated by Django 3.0.10 on 2021-01-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0036_report_docx_finding_template'),
        ('commandcenter', '0005_auto_20201102_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='default_docx_finding_template',
            field=models.ForeignKey(blank=True, help_text='Select a default Word Finding template', limit_choices_to={'doc_type__doc_type__iexact': 'docx'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportconfiguration_finding_docx_set', to='reporting.ReportTemplate'),
        ),
    ]
