# Generated by Django 3.0.10 on 2020-11-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0021_auto_20201119_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cvss',
            field=models.TextField(blank=True, help_text='Calculate the cvss score', null=True, verbose_name='CVSS Score'),
        ),
    ]
