# Generated by Django 3.0.10 on 2020-12-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0022_finding_cvss'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfindinglink',
            name='cvss',
            field=models.TextField(blank=True, help_text='Calculate the cvss score', null=True, verbose_name='CVSS Score'),
        ),
    ]
