# Generated by Django 3.0.10 on 2020-12-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0023_reportfindinglink_cvss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='cvss',
            field=models.CharField(blank=True, help_text='Calculate the cvss score', max_length=255, null=True, verbose_name='CVSS Score'),
        ),
    ]
