# Generated by Django 3.0.10 on 2020-12-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0025_auto_20201203_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='cvss_score',
            field=models.CharField(blank=True, help_text='Calculate the cvss score', max_length=255, null=True, verbose_name='CVSS Score'),
        ),
    ]
