# Generated by Django 3.0.10 on 2020-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0026_auto_20201203_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_score',
            field=models.CharField(blank=True, help_text='Calculate the cvss score', max_length=255, null=True, verbose_name='CVSS Score'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='Calculate the cvss vector', max_length=255, null=True, verbose_name='CVSS Vector'),
        ),
    ]
