# Generated by Django 3.0.10 on 2020-12-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0027_auto_20201204_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(help_text='Type of Endpoint (e.g. API, UI)', max_length=255, unique=True, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Endpoint type',
                'verbose_name_plural': 'Endpoint types',
                'ordering': ['endpoint_type'],
            },
        ),
        migrations.CreateModel(
            name='ScopeDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_domain', models.CharField(default='Domain', help_text='Tested domains', max_length=255, verbose_name='Domain')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Report')),
            ],
        ),
        migrations.CreateModel(
            name='DomainEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_endpoint', models.CharField(help_text='Tested endpoint', max_length=255, null=True, verbose_name='Endpoint')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.ScopeDomain')),
                ('endpoint_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.EndpointType')),
            ],
        ),
    ]
