# Generated by Django 3.0.10 on 2020-12-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0028_domainendpoint_endpointtype_scopedomain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScopeDomain',
            new_name='Domain',
        ),
    ]
