# Generated by Django 3.0.10 on 2020-12-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0030_auto_20201217_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endpointtype',
            options={'ordering': ['endpoint'], 'verbose_name': 'Endpoint type', 'verbose_name_plural': 'Endpoint types'},
        ),
        migrations.RenameField(
            model_name='endpointtype',
            old_name='endpoint_type',
            new_name='endpoint',
        ),
    ]
