# Generated by Django 3.0.10 on 2020-12-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0031_auto_20201217_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endpointtype',
            options={'ordering': ['endpoint_type'], 'verbose_name': 'Endpoint type', 'verbose_name_plural': 'Endpoint types'},
        ),
        migrations.RenameField(
            model_name='endpointtype',
            old_name='endpoint',
            new_name='endpoint_type',
        ),
    ]
