# Generated by Django 3.0.10 on 2021-01-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0032_auto_20201218_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfindinglink',
            name='external_tracker',
            field=models.TextField(blank=True, help_text='Add the external flaw/jira link', null=True, verbose_name='External Flaw'),
        ),
        migrations.AddField(
            model_name='reportfindinglink',
            name='internal_tracker',
            field=models.TextField(blank=True, help_text='Add the internal task link', null=True, verbose_name='Internal Task'),
        ),
    ]
