# Generated by Django 3.0.10 on 2021-01-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0033_auto_20210108_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfindinglink',
            name='external_tracker',
            field=models.CharField(blank=True, help_text='Add the external flaw/jira link', max_length=255, null=True, verbose_name='External Flaw'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='internal_tracker',
            field=models.CharField(blank=True, help_text='Add the internal task link', max_length=255, null=True, verbose_name='Internal Task'),
        ),
    ]
