# Generated by Django 3.0.10 on 2021-01-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0034_auto_20210108_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tested_version',
            field=models.CharField(help_text='Provide the tested version for this report', max_length=255, null=True, verbose_name='Tested Version'),
        ),
    ]
