# Generated by Django 3.0.10 on 2021-01-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0035_report_tested_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='docx_finding_template',
            field=models.ForeignKey(help_text='Select the Word template to use for this report findings', limit_choices_to={'doc_type__doc_type__iexact': 'docx'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporttemplate_finding_docx_set', to='reporting.ReportTemplate'),
        ),
    ]
