# Generated by Django 3.0.10 on 2021-01-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0036_report_docx_finding_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tested_version',
            field=models.CharField(blank=True, help_text='Provide the tested version for this report', max_length=255, null=True, verbose_name='Tested Version'),
        ),
    ]
